w :
	gcc -std=c17 main.c -I SDL2\include -L SDL2\lib -Wall -lmingw32 -lSDL2main -lSDL2 -o main

l :
	gcc main.c -o main -L./lib -I./include -lSDL2-2.0
	./main

wall :
	gcc -Wall -Wextra main.c -o main -L./lib -I./include -lSDL2-2.0
